### PR TITLE
CD-235473 Change Resque.redis to Resque::Worker redis and replace Resque::Worker to self.class

### PR DESCRIPTION
**Pull request by revathi-murali**
## Reviewers

-  [ ] @johnny-lai 

## Summary of Change

As a part of redis v6 project, enterprise supports two kinds of resque workers - Resque::Worker(for redis v3) and Resque::SSLWorker(for redis v6). Also resque workers talks to its own redis and not Resque.redis. 

Hence making changes to replace Resque.redis with Resque::Worker redis

### CODE REVIEW

**Comment by johnny-lai** [comment]
lgtm

**Comment by johnny-lai** [comment]
The gem may have rspecs. We should at least update the rspec for these changes.

**Comment by revathi-murali** [comment]
@johnny-lai There is no rspecs in the gem to handle this usecase. The only rspec it has is just a test case for creating a worker - https://github.com/coupa/resque-round-robin/blob/master/spec/round-robin_spec.rb

Let me check if I can add a test case

**Comment by revathi-murali** [comment]
[lockit v4.9.3] merged via Lockit CLI on 2021-02-25 12:32:08.259995 +0530 IST m=+6.106346570

**Pull request merged**
